<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>13.0</LangVersion>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentQuotaTray.Core\AgentQuotaTray.Core.csproj" />
  </ItemGroup>

</Project>
