<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>13.0</LangVersion>
    <ApplicationIcon>..\..\assets\limit.ico</ApplicationIcon>
    <AssemblyTitle>Lim'it</AssemblyTitle>
    <Product>Lim'it</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LimitTray.Core\LimitTray.Core.csproj" />
  </ItemGroup>

</Project>
